### ISSUE TITLE
Getting following while accessing UI: SyntaxError - ../chroma-db-ui/views/index.erb:21: syntax error, unexpected `end' ...t_buf.<< "      ".freeze; - end ; @_out_buf.<< "\n".freeze

### ISSUE THREAD

**Issue by swapanshridhar** [flanker/chroma-db-ui#1]
Made following changes to get the app to run, as it was failing in `bundle install` before

- Installed Ruby version 3.2.2, as 2.x version was failing in bundle install for incompatible chroma-db version: 

```
$ ruby -v    
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin20
```

- Updated Gemfile with other dependencies as app was failing to come up:

```
$ cat Gemfile 
source 'https://rubygems.org'

gem 'chroma-db'
gem 'sinatra'
gem 'puma'        <-----------------
gem "dead_end"  <-----------------
```

Post above changes, `bundle install` went fine.

Started the app as:

```$ ruby app.rb
== Sinatra (v3.1.0) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Puma version: 6.3.1 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 37747
* Listening on http://127.0.0.1:4567
* Listening on http://[::1]:4567
Use Ctrl-C to stop
```

but as soon as i access the URL, below is what i see on terminal and UI:

Terminal:

```* Listening on http://127.0.0.1:4567
* Listening on http://[::1]:4567
Use Ctrl-C to stop



2023-08-23 18:57:08 - SyntaxError - ..../chroma-db-ui/views/index.erb:21: syntax error, unexpected `end'
...t_buf.<< "      ".freeze; - end ; @_out_buf.<< "\n".freeze
...                            ^~~
.../chroma-db-ui/views/index.erb:30: syntax error, unexpected `else'
..._buf.<< "      ".freeze; - else ; @_out_buf.<< "\n".freeze
...                           ^~~~
.../chroma-db-ui/views/index.erb:32: syntax error, unexpected `end'
...t_buf.<< "      ".freeze; - end ; @_out_buf.<< "\n".freeze
...                            ^~~
.../chroma-db-ui/views/index.erb:36: syntax error, unexpected `else'
..._buf.<< "      ".freeze; - else ; @_out_buf.<< "\n".freeze
...                           ^~~~
..../chroma-db-ui/views/index.erb:38: syntax error, unexpected `end'
...t_buf.<< "      ".freeze; - end ; @_out_buf.<< "\n".freeze
...                            ^~~
..../chroma-db-ui/views/index.erb:57: syntax error, unexpected `end'
...t_buf.<< "      ".freeze; - end ; @_out_buf.<< "\n".freeze
...                            ^~~
:
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:371:in `class_eval'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:371:in `eval_compiled_method'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:366:in `bind_compiled_method'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:341:in `compile_template_method'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:158:in `compiled_method'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:208:in `evaluate'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:104:in `render'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:866:in `render'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:748:in `erb'
	app.rb:17:in `block in <main>'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1763:in `block in compile!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1084:in `route_eval'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1066:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1115:in `block in process_route'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `catch'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1113:in `process_route'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1064:in `block in route!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `each'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1061:in `route!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1185:in `block in dispatch!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1180:in `dispatch!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `block in call!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `catch'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1156:in `invoke'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:996:in `call!'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:985:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/xss_header.rb:20:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/path_traversal.rb:18:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/json_csrf.rb:28:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/base.rb:53:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-protection-3.1.0/lib/rack/protection/frame_options.rb:33:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/logger.rb:17:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/common_logger.rb:38:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:261:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:254:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/rack-2.2.8/lib/rack/method_override.rb:24:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/show_exceptions.rb:23:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:219:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:2074:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `block in call'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1849:in `synchronize'
	/usr/local/lib/ruby/gems/3.2.0/gems/sinatra-3.1.0/lib/sinatra/base.rb:1633:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/configuration.rb:270:in `call'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/request.rb:100:in `block in handle_request'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/thread_pool.rb:344:in `with_force_shutdown'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/request.rb:99:in `handle_request'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/server.rb:443:in `process_client'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/server.rb:245:in `block in run'
	/usr/local/lib/ruby/gems/3.2.0/gems/puma-6.3.1/lib/puma/thread_pool.rb:151:in `block in spawn_thread'
127.0.0.1 - - [23/Aug/2023:18:57:08 -0700] "GET /__sinatra__/500.png HTTP/1.1" 200 24378 0.0187
127.0.0.1 - - [23/Aug/2023:18:57:08 -0700] "GET /favicon.ico HTTP/1.1" 404 469 0.0023
```

UI:
<img width="1332" alt="Screen Shot 2023-08-23 at 6 58 53 PM" src="https://github.com/flanker/chroma-db-ui/assets/1879146/3866ea8f-da71-4f28-a880-f275442a3fe4">

What is expected?

Able to connect to the Chroma DB.

**Comment by flanker** [comment]
hi @swapanshridhar 

Thanks for your issue.

For the missing dependencies issue, I've pushed a fix to add the required dependencies. In commit 0b43ebadfa5a517a6606642a2ab0f3b5487bf44c

Note: only `puma` is required as `dead_end` is only used for better error message I guess.

**Comment by flanker** [comment]
And I'm not sure what happens for the syntax error. Did you change any code in `views/index.erb` file?

I tried with the same versions as in your error log, but it works:

```
== Sinatra (v3.1.0) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Puma version: 6.3.0 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 52425
* Listening on http://127.0.0.1:4567
* Listening on http://[::1]:4567
Use Ctrl-C to stop
127.0.0.1 - - [24/Aug/2023:14:01:02 +0800] "GET / HTTP/1.1" 200 660 0.0593
```

**Comment by swapanshridhar** [comment]
@flanker 

>Note: only puma is required as dead_end is only used for better error message I guess.

Yes, makes sense. I added `dead_end` based on my GSearch in hope of getting better error to resolve the issue.


>And I'm not sure what happens for the syntax error. Did you change any code in views/index.erb file?

I haven't made any change to the `views/index.erb` file. Infact other than `Gemfile`, i haven't made any changes:

To confirm, my latest git details are:

```

$ pwd
..../chroma-db-ui
```

```

$ git log
commit 4c063c0d5267fb1c53956fa92857f6055fddc345 (HEAD -> main, origin/main, origin/HEAD)
Author: FENG Zhichao <flankerfc@gmail.com>
Date:   Sun Aug 6 09:07:26 2023 +0800

    A little bit of styling.

commit 3b29403f64d3de4403657f12b4b96679c8f9b858
Author: Feng Zhichao <flankerfc@gmail.com>
Date:   Sun Aug 6 09:07:13 2023 +0800

    Replace with new screenshot

```

```
$ git status 
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Gemfile
	modified:   Gemfile.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

```
 git status views/index.erb
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```


One more point is that I have my chromaDB running on a different node and is accessible. Thus I have imported the ENV VAR as:

`export CHROMA_URL=http://<PrivateIP>:8000`

Accessibly checks for ChromaDB :

Heartbeat is coming and I have used same Chroma DB with my locally running Python code and that works.
<img width="594" alt="Screen Shot 2023-08-24 at 12 34 09 AM" src="https://github.com/flanker/chroma-db-ui/assets/1879146/182b67e2-cc01-4e49-8825-4566c46cab83">

**Comment by swapanshridhar** [comment]
@flanker 

The only difference I see is:

What you posted:
`* Puma version: 6.3.0 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")`


What I have:
`* Puma version: 6.3.1 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")`


Puma version is different. Can that be the issue ?

**Comment by swapanshridhar** [comment]
Confirming Puma version may not be the issue, as I tried with 6.3.0 and still the same issue.

My Ruby version is:

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin20]
```

Whats the one that you are using ?

**Comment by flanker** [comment]
I am running the same Ruby:

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
```

Are familiar with erb? Could you please change the index.erb to a very simple template to see if it works. like:

```
<!DOCTYPE html>
<html lang="en-us">
<head>
  <title>Chroma DB UI</title>
</head>
<body>
<%- if true %>
  <%= "hello world" %>
<%- end %>
</body>
</html>
```

**Comment by swapanshridhar** [comment]
@flanker 
Used above index.erb. That too gives issue:


Line No: `.../chroma-db-ui/views/index.erb:9`

```
ruby app.rb
== Sinatra (v3.1.0) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Puma version: 6.3.0 (ruby 3.2.2-p53) ("Mugi No Toki Itaru")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 46097
* Listening on http://127.0.0.1:4567
* Listening on http://[::1]:4567
Use Ctrl-C to stop
2023-08-24 01:16:04 - SyntaxError - .../chroma-db-ui/views/index.erb:9: syntax error, unexpected `end'
; - end
    ^~~
:
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:371:in `class_eval'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:371:in `eval_compiled_method'
	/usr/local/lib/ruby/gems/3.2.0/gems/tilt-2.2.0/lib/tilt/template.rb:366:in `bind_compiled_method'
```


Further, checking online for syntaz validation for erb file, I see this:

This also point to line no. 9
 


<img width="1270" alt="Screen Shot 2023-08-24 at 1 27 05 AM" src="https://github.com/flanker/chroma-db-ui/assets/1879146/4e8b466e-82e5-4b0d-815c-077eee235a90">

https://extendsclass.com/ruby-tester.html

I am running it on MacOS.

**Comment by flanker** [comment]
@swapanshridhar 

I did reproduce the issue. Looks like the following code is not standard ERB syntax:

```
<%- if true %>
  <%= "hello world" %>
<%- end %>
```

It should be: (Remove the `-` symbols)

```
<% if true %>
  <%= "hello world" %>
<% end %>
```

It worked on my machine I think that was because I had some other gems (haven't found which one).

anyway, I've pushed a new commit (23d79cf6e23d0f9fd0575529d7897243dd8e6c9a). You can have a try.

**Comment by swapanshridhar** [comment]
@flanker Confirming that with the latest pull (above change), UI came up just fine and shows the embedding.

Thanks for the quick and prompt fix. Much appreciated!
